controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      max_vel_x: 0.5
      max_vel_theta: 1.0
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20

      critics: ["RotateToGoal", "ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      RotateToGoal:
        scale: 32.0

      GoalAlign:
        scale: 24.0

      PathAlign:
        scale: 32.0

      PathDist:
        scale: 32.0

      GoalDist:
        scale: 24.0

      ObstacleFootprint:
        scale: 0.02

    goal_checker:
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    default_bt_xml_filename: "navigate_w_replanning_time.xml"

